global{
  DENY_LOGIN="no" 
  PORT="21"
  PASSIVE_PORTS="0"
  DATAPORT20="no"
  ADMIN_PASS="x"
  XFER_BUFSIZE="64000"
  CHANGE_BUFSIZE="no"
  XFER_DELAY="0"
  SHOW_HIDDEN_FILES="yes"
  SHOW_NONREADABLE_FILES="yes"
  ALLOW_FXP="yes"
  CONTROL_TIMEOUT="86400"
  DATA_TIMEOUT="86400"
  RATIO="none"
  ROOTDIR="/"
  UMASK="022"
  LOGFILE=""
  HELLO_STRING="bftpd %v at %i ready."
  AUTO_CHDIR="/"
  AUTH="PASSWD"
  RESOLVE_CLIENT_IP="no"
  MOTD_GLOBAL=""
  MOTD_USER="/.ftpmotd"
  RESOLVE_UIDS="yes"
  DO_CHROOT="no"
  BIND_TO_ADDR="any"
  PATH_FTPUSERS=""
  ALLOWCOMMAND_DELE="yes"
  ALLOWCOMMAND_STOR="yes"
  ALLOWCOMMAND_SITE="yes"
  HIDE_GROUP=""
  QUIT_MSG="See you later..."
  USERLIMIT_GLOBAL="0"
  USERLIMIT_SINGLEUSER="0"
  USERLIMIT_HOST="0"
  GZ_UPLOAD="no"
  GZ_DOWNLOAD="no"
}

user ftp {
  ANONYMOUS_USER="yes"
}

user anonymous {
  ALIAS="ftp"
}

user root {
  ALIAS="ftp"
}


